#database details -------------------------------------------------------------------------------------------------
spring.datasource.url=jdbc:mysql://localhost:3306/medicine_donation
spring.datasource.username=nimbusnex
spring.datasource.password=nimbusnex
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.security.user.name=user
spring.security.user.password=user